"""added attendance columns

Revision ID: 3d823493dbae
Revises: b4b11eb5d79e
Create Date: 2026-01-17 18:29:54.730845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d823493dbae'
down_revision = 'b4b11eb5d79e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('delay_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_update', sa.DateTime(), nullable=True))

    with op.batch_alter_table('van_location', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('driver_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('van_location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driver_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'driver', ['driver_id'], ['id'])

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('last_update')
        batch_op.drop_column('delay_time')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
