"""Added phone_number to Driver

Revision ID: b4b11eb5d79e
Revises: c8ed47c0646e
Create Date: 2026-01-16 13:48:21.132473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4b11eb5d79e'
down_revision = 'c8ed47c0646e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('driver', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=15), nullable=True))

    with op.batch_alter_table('van_location', schema=None) as batch_op:
        #batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('driver_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('van_location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driver_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'driver', ['driver_id'], ['id'])

    with op.batch_alter_table('driver', schema=None) as batch_op:
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
